# Generated by Django 4.2.6 on 2023-10-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elementos',
            fields=[
                ('fechaElemento', models.DateField()),
                ('nombreElemento', models.CharField(max_length=25)),
                ('categoriaElemento', models.CharField(choices=[('C', 'Consumible'), ('D', 'Devolutivo')], default='C', max_length=25)),
                ('estadoElemento', models.CharField(choices=[('G', 'Garantia'), ('B', 'Baja'), ('D', 'Disponible')], default='D', max_length=25)),
                ('descripcionElemento', models.CharField(max_length=25)),
                ('observacionElemento', models.CharField(max_length=25)),
                ('cantidadElemento', models.IntegerField()),
                ('valorUnidadElemento', models.IntegerField()),
                ('valorTotalElemento', models.IntegerField()),
                ('serialSenaElemento', models.CharField(max_length=25)),
                ('facturaElemento', models.ImageField(blank=True, null=True, upload_to='facturaElemento/')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('fechaEntrega', models.DateField()),
                ('fechaDevolucion', models.DateField()),
                ('nombreEntrega', models.CharField(max_length=25)),
                ('nombreRecibe', models.CharField(max_length=25)),
                ('observacionesPrestamo', models.CharField(max_length=25)),
                ('firmaDigital', models.ImageField(blank=True, null=True, upload_to='firmaDigital/')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SalidaConsumibles',
            fields=[
                ('nombreEntrega', models.CharField(max_length=25)),
                ('nombreRecibe', models.CharField(max_length=25)),
                ('observacionesPrestamo', models.CharField(max_length=25)),
                ('firmaDigital', models.ImageField(blank=True, null=True, upload_to='firmaDigital/')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UsuariosSena',
            fields=[
                ('nombre', models.CharField(max_length=25)),
                ('apellidoo', models.CharField(max_length=25)),
                ('tipoIdentificacion', models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('TI', 'Tarjeta de identidad'), ('PEP', 'Permiso especial de permanencia'), ('O', 'Otro')], default='CC', max_length=25)),
                ('numeroIdentificacion', models.CharField(max_length=25)),
                ('correoSena', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=10)),
                ('rol', models.CharField(choices=[('superAdmin', 'super Administrador'), ('I', 'instructor'), ('M', 'Monitor')], default='I', max_length=25)),
                ('cuentadante', models.CharField(choices=[('adminS', 'administrador Solidario'), ('adminD', 'administrador Directo'), ('monitor', 'monitor')], default='adminD', max_length=25)),
                ('tipoContrato', models.CharField(choices=[('P', 'Planta'), ('C', 'Contratista'), ('A', 'Aprendiz')], default='P', max_length=25)),
                ('duracionContrato', models.CharField(max_length=25)),
                ('estadoUsuario', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=25)),
                ('contraSena', models.CharField(max_length=25)),
                ('validacionContraSena', models.CharField(max_length=25)),
                ('fotoUsuario', models.ImageField(blank=True, null=True, upload_to='usuarioFoto/')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
