# Generated by Django 4.2.5 on 2023-11-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsuariosSena', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariossena',
            name='recovery_token',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usuariossena',
            name='email',
            field=models.EmailField(max_length=35),
        ),
    ]
