# Generated by Django 4.2.5 on 2023-11-10 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UsuariosSena', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestamoConsumible',
            fields=[
                ('cantidad_prestada', models.PositiveIntegerField()),
                ('fecha_entrega', models.DateField()),
                ('serial_elemento', models.CharField(max_length=100)),
                ('nombre_solicitante', models.CharField(max_length=100)),
                ('observaciones_prestamo', models.TextField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('elemento_consumible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsuariosSena.elementos')),
            ],
        ),
    ]
