# Generated by Django 4.2.6 on 2023-11-10 20:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("UsuariosSena", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="usuariossena",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="usuariossena",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="usuariossena",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="usuariossena",
            name="username",
        ),
    ]
