# Generated by Django 4.2.6 on 2023-11-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsuariosSena', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='estado_prestamo',
            new_name='estadoPrestamo',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='estado',
        ),
        migrations.AlterField(
            model_name='elementosconsumible',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
