# Generated by Django 4.2.5 on 2023-11-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsuariosSena', '0002_usuariossena_recovery_token_alter_usuariossena_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosinventariodevolutivo',
            name='estado',
            field=models.CharField(choices=[('G', 'Garantia'), ('B', 'Baja'), ('D', 'Disponible'), ('P', 'Prestamo')], default='D', max_length=25),
        ),
        migrations.AlterField(
            model_name='usuariossena',
            name='cuentadante',
            field=models.CharField(choices=[('superAdmin', 'Super Admin'), ('adminS', 'administrador Solidario'), ('adminD', 'administrador Directo'), ('monitor', 'monitor')], default='adminD', max_length=25),
        ),
        migrations.AlterField(
            model_name='usuariossena',
            name='rol',
            field=models.CharField(choices=[('superAdmin', 'Super Administrador'), ('I', 'Instructor'), ('M', 'Monitor')], default='I', max_length=25),
        ),
    ]
