# Generated by Django 4.2.6 on 2023-11-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UsuariosSena", "0003_alter_productosinventariodevolutivo_estado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="elementosconsumible",
            name="disponible",
            field=models.IntegerField(default=0),
        ),
    ]
