# Generated by Django 4.2.1 on 2023-11-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsuariosSena', '0003_elementosconsumible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='estado',
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estado_prestamo',
            field=models.CharField(choices=[('V', 'Vigente'), ('F', 'Finalizado')], default='V', max_length=25),
        ),
    ]
