# Generated by Django 4.2.1 on 2023-11-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsuariosSena', '0004_remove_prestamo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estado_prestamo',
            field=models.CharField(max_length=15),
        ),
    ]
