# Generated by Django 4.2.6 on 2023-11-28 04:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("UsuariosSena", "0004_elementosconsumible_disponible"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elementosconsumible",
            name="disponible",
        ),
    ]
