# Generated by Django 4.2.6 on 2023-11-28 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("UsuariosSena", "0005_remove_elementosconsumible_disponible"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventarioConsumible",
            fields=[
                ("fechaAdquisicion", models.DateField(auto_now_add=True)),
                ("cantidadElemento", models.IntegerField()),
                ("costoTotalElemento", models.IntegerField(blank=True, null=True)),
                ("observacionElemento", models.CharField(max_length=25)),
                (
                    "facturaElemento",
                    models.ImageField(
                        blank=True, null=True, upload_to="facturaElemento/"
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="ProductosInventarioConsumible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreElemento", models.CharField(max_length=25)),
                (
                    "categoriaElemento",
                    models.CharField(
                        choices=[("D", "Devolutivo"), ("C", "Consumible")],
                        default="C",
                        max_length=25,
                    ),
                ),
                (
                    "estadoElemento",
                    models.CharField(
                        choices=[("D", "Disponible"), ("A", "Agotado")],
                        default="D",
                        max_length=25,
                    ),
                ),
                ("descripcionElemento", models.CharField(max_length=25)),
                ("costoUnidadElemento", models.IntegerField()),
                ("disponible", models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name="ElementosConsumible",
        ),
        migrations.AlterField(
            model_name="entregaconsumible",
            name="nombre_solicitante",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitudes_recibidas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="entregaconsumible",
            name="responsable_Entrega",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entregas_realizadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inventarioconsumible",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="UsuariosSena.productosinventarioconsumible",
            ),
        ),
        migrations.AlterField(
            model_name="entregaconsumible",
            name="nombreElemento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entregas",
                to="UsuariosSena.inventarioconsumible",
            ),
        ),
    ]
