# Generated by Django 4.2.1 on 2023-11-16 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsuariosSena', '0005_alter_prestamo_estado_prestamo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='estado_prestamo',
            new_name='estadoPrestamo',
        ),
    ]
