# Generated by Django 4.2.6 on 2023-11-28 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "UsuariosSena",
            "0006_inventarioconsumible_productosinventarioconsumible_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventarioconsumible",
            name="producto",
        ),
        migrations.AddField(
            model_name="inventarioconsumible",
            name="productoConsumible",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="UsuariosSena.productosinventarioconsumible",
            ),
        ),
    ]
