# Generated by Django 4.2.6 on 2023-11-28 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("UsuariosSena", "0007_remove_inventarioconsumible_producto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventarioconsumible",
            name="productoConsumible",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="UsuariosSena.productosinventarioconsumible",
            ),
        ),
    ]
