# Generated by Django 4.2.6 on 2023-11-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UsuariosSena", "0008_alter_inventarioconsumible_productoconsumible"),
    ]

    operations = [
        migrations.AddField(
            model_name="entregaconsumible",
            name="valorTotalEntrega",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
