# Generated by Django 4.2.6 on 2023-11-29 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("UsuariosSena", "0009_entregaconsumible_valortotalentrega"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElementosConsumible",
            fields=[
                ("fechaAdquisicion", models.DateField(auto_now_add=True)),
                ("nombreElemento", models.CharField(max_length=25)),
                (
                    "categoriaElemento",
                    models.CharField(
                        choices=[("D", "Devolutivo"), ("C", "Consumible")],
                        default="C",
                        max_length=25,
                    ),
                ),
                (
                    "estadoElemento",
                    models.CharField(
                        choices=[("D", "Disponible"), ("A", "Agotado")],
                        default="D",
                        max_length=25,
                    ),
                ),
                ("descripcionElemento", models.CharField(max_length=25)),
                ("observacionElemento", models.CharField(max_length=25)),
                ("cantidadElemento", models.IntegerField()),
                ("costoUnidadElemento", models.IntegerField()),
                ("costoTotalElemento", models.IntegerField(blank=True, null=True)),
                (
                    "facturaElemento",
                    models.ImageField(
                        blank=True, null=True, upload_to="facturaElemento/"
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="inventarioconsumible",
            name="productoConsumible",
        ),
        migrations.RemoveField(
            model_name="entregaconsumible",
            name="valorTotalEntrega",
        ),
        migrations.DeleteModel(
            name="ProductosInventarioConsumible",
        ),
        migrations.AlterField(
            model_name="entregaconsumible",
            name="nombreElemento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entregas",
                to="UsuariosSena.elementosconsumible",
            ),
        ),
        migrations.DeleteModel(
            name="InventarioConsumible",
        ),
    ]
