# Generated by Django 4.2.6 on 2023-11-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "UsuariosSena",
            "0011_productosinventarioconsumible_inventarioconsumible_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="entregaconsumible",
            old_name="nombreElemento",
            new_name="idC",
        ),
        migrations.AlterField(
            model_name="entregaconsumible",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
