# Generated by Django 4.2.6 on 2023-11-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UsuariosSena", "0012_rename_nombreelemento_entregaconsumible_idc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productosinventarioconsumible",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
